name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
  
  check_fmt:
    name: Check fmt
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: fmt
      run: cargo fmt -- --check
